# Site
repository: yuchenWYC/yuchenwyc.github.io
# favicon: images/favicon.ico

# Personal info
name: Yuchen Wang
title: undergraduate CS student at the University of Toronto
email: rainawang217@gmail.com
website: yuchenwyc.github.io

# Social links
twitter_username: YuchenW10030993
github_username:  yuchenWYC
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: yuchenwyc
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yuchen and I'm a third-year CS student at the University of Toronto. I was a summer research student under Professor Bo Wang. I am an incoming summer 
  research student under Professor Roger Grosse.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Machine Learning and CS, some of my other interests and hobbies are:
   - Reading scientific articles
   - Painting & drawing
   - Board games!
   - Having coffee chats with new people

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
