# Site
repository: yuchenWYC/yuchenwyc.github.io
favicon: images/lion.png

# Personal info
name: Yuchen Wang
title: undergrad @ UofT
email: rainawang217@gmail.com

# Social links
twitter_username: YuchenW10030993
github_username:  yuchenWYC
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: yuchenwyc
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
I am a third-year Computer Science student at the University of Toronto. I also study a little statistics and mathematics, because mathematics is the foundation of statistics, and statistics is the foundation of all subjects. I currently work under Professor Roger Grosse in deep learning problems.
I found the area of deep learning very fascinating and essential to the current innovation process of both academic and industry world. You are welcome to contact me and start a conversation if you have similar interests. (Find out my experiences and contact information in my CV below)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Machine Learning and CS, some of my other interests and hobbies are:
   - Reading scientific articles (I could easily get satisfied when I gain a little more knowledge)
   - Painting & drawing
   - Board games!
   - Having coffee chats with new people

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
